import requests from './ajax'

export const getGoods = (data: any) => requests.post('/shipping/Order/getGoodsList', data)
export const getNewGoods = (data: any) => requests.post('/shipping/Order/flushGoods', data)
export const pushShop = (data: any) => requests.post('/shipping/Order/pushToShop', data)
export const deleteGoods = (data: any) => requests.post('/shipping/Order/deleteGoods', data)
export const getCart = (data: any) => requests.post('/shipping/Order/getCartList', data)
export const deleteCart = (data: any) => requests.post('/shipping/Order/deleteCart', data)
export const editCart = (data: any) => requests.post('/shipping/Order/setCartGoodsNum', data)
export const getRate = (data: any = {}) => requests.post('/shipping/Order/getExchangeRate', data)
export const orderInfo = (data: any) => requests.post('/shipping/Order/preview', data)
export const orderCreate = (data: any) => requests.post('/shipping/Order/create', data)
export const orderPay = (data: any) => requests.post('/shipping/Order/pay', data)
export const getOrderList = (data: any) => requests.post('/shipping/StoreOrder/getOrderList', data)
export const syncOrder = (data: any) => requests.post('/shipping/StoreOrder/syncOrder', data)
export const editRemark = (data: any) => requests.post('/shipping/StoreOrder/editRemark', data)
export const editAddress = (data: any) => requests.post('/shipping/StoreOrder/editAddress', data)
export const getShippingMethod = (data: any) => requests.post('/shipping/StoreOrder/getShippingMethod', data)
export const changeShippingMethod = (data: any) => requests.post('/shipping/StoreOrder/changeShippingMethod', data)
export const fulfillment = (data: any) => requests.post('/shipping/StoreOrder/fulfillment', data)
export const createDeliveryOrder = (data: any) => requests.post('/shipping/StoreOrder/createDeliveryOrder', data)
export const getDeliveryOrderList = (data: any) => requests.post('/shipping/StoreOrder/getDeliveryOrderList', data)
export const getDeliveryOrderInfo = (data: any) => requests.post('/shipping/StoreOrder/getDeliveryOrderInfo', data)
export const payOrder = (data: any) => requests.post('/shipping/StoreOrder/pay', data)
export const canalOrder = (data: any) => requests.post('/shipping/StoreOrder/canal', { order_number: data?.order_number })
export const storeTrack = (data: any) => requests.post('/shipping/StoreOrder/tracking', data)
export const updateFreightCode = (data: any) => requests.post('/shipping/Order/updateFreightCode', data)
export const batchPushToShop = (data: any) => requests.post('/shipping/Order/batchPushToShop', data)
