const en = [
  'Search', 'Please enter the product keywords', 'Please enter the product keywords / link',
  'Product filters', 'Category', 'Price', 'MOQ', 'Fulfillment', 'Supplier quality', 'Product specs', 'All filters',
  'Live filters ready', 'No filters selected', 'Results for', 'live catalog', 'Sort by', 'Relevance', 'Monthly sales',
  'Price: low to high', 'Price: high to low', 'Grid view', '1-piece dropship', 'Find related products',
  'Add to my products', 'piece', 'pieces', '48h dispatch', 'Invoice', 'List product', 'Chat now',
  'Browsing history', 'Keep looking for', 'Frequently searched:', 'Best-Sellers Section', 'More Products',
  'Local Stock Zone', 'Recommended Products', 'Cost Calculator', 'Pricing', 'Integrations', 'Support',
  'Resources', 'Blog', 'Procurement Guides', 'Video Tutorials', 'Case Studies', 'Industry Reports', 'FAQ',
  'Privacy Policy', 'Terms & Conditions', 'Find us on', 'We Accept',
]

const rows: Record<string, string[]> = {
  'zh-CN': ['搜索','请输入商品关键词','请输入商品关键词 / 链接','产品筛选','分类','价格','起订量','履约','供应商质量','产品规格','所有筛选','实时筛选就绪','未选择筛选条件','搜索结果','实时目录','排序方式','相关性','月销量','价格：从低到高','价格：从高到低','网格视图','1件代发','查找相关商品','添加到我的商品','件','件','48小时发货','发票','发布商品','立即沟通','浏览历史','继续搜索','热门搜索：','畅销专区','更多产品','本地库存专区','推荐产品','成本计算器','定价','集成','支持','资源','博客','采购指南','视频教程','案例研究','行业报告','常见问题','隐私政策','条款与条件','关注我们','我们接受'],
  'es-ES': ['Buscar','Introduce palabras clave del producto','Introduce palabras clave o enlace','Filtros de productos','Categoría','Precio','Pedido mínimo','Cumplimiento','Calidad del proveedor','Especificaciones','Todos los filtros','Filtros en tiempo real listos','Sin filtros seleccionados','Resultados para','catálogo en tiempo real','Ordenar por','Relevancia','Ventas mensuales','Precio: menor a mayor','Precio: mayor a menor','Vista de cuadrícula','Envío de una unidad','Buscar productos relacionados','Añadir a mis productos','unidad','unidades','Envío en 48 h','Factura','Publicar producto','Chatear ahora','Historial de navegación','Seguir explorando','Búsquedas frecuentes:','Más vendidos','Más productos','Inventario local','Productos recomendados','Calculadora de costes','Precios','Integraciones','Soporte','Recursos','Blog','Guías de compras','Tutoriales en vídeo','Casos de éxito','Informes del sector','Preguntas frecuentes','Política de privacidad','Términos y condiciones','Síguenos','Aceptamos'],
  'fr-FR': ['Rechercher','Saisissez les mots-clés du produit','Saisissez les mots-clés ou le lien','Filtres produits','Catégorie','Prix','MOQ','Exécution','Qualité du fournisseur','Caractéristiques','Tous les filtres','Filtres en direct prêts','Aucun filtre sélectionné','Résultats pour','catalogue en direct','Trier par','Pertinence','Ventes mensuelles','Prix : croissant','Prix : décroissant','Vue grille','Livraison à l’unité','Trouver des produits similaires','Ajouter à mes produits','pièce','pièces','Expédition sous 48 h','Facture','Publier le produit','Discuter maintenant','Historique','Continuer à explorer','Recherches fréquentes :','Meilleures ventes','Plus de produits','Stock local','Produits recommandés','Calculateur de coûts','Tarifs','Intégrations','Assistance','Ressources','Blog','Guides d’achat','Tutoriels vidéo','Études de cas','Rapports sectoriels','FAQ','Politique de confidentialité','Conditions générales','Suivez-nous','Nous acceptons'],
  'de-DE': ['Suchen','Produktbegriffe eingeben','Produktbegriffe oder Link eingeben','Produktfilter','Kategorie','Preis','Mindestbestellmenge','Abwicklung','Lieferantenqualität','Produktspezifikationen','Alle Filter','Live-Filter bereit','Keine Filter ausgewählt','Ergebnisse für','Live-Katalog','Sortieren nach','Relevanz','Monatliche Verkäufe','Preis: aufsteigend','Preis: absteigend','Rasteransicht','Einzelstück-Dropshipping','Ähnliche Produkte finden','Zu meinen Produkten hinzufügen','Stück','Stück','Versand in 48 Std.','Rechnung','Produkt veröffentlichen','Jetzt chatten','Browserverlauf','Weiter entdecken','Häufig gesucht:','Bestseller','Weitere Produkte','Lokaler Bestand','Empfohlene Produkte','Kostenrechner','Preise','Integrationen','Support','Ressourcen','Blog','Einkaufsleitfäden','Video-Tutorials','Fallstudien','Branchenberichte','FAQ','Datenschutzrichtlinie','Geschäftsbedingungen','Folgen Sie uns','Wir akzeptieren'],
  'pt-BR': ['Buscar','Digite palavras-chave do produto','Digite palavras-chave ou link','Filtros de produtos','Categoria','Preço','Pedido mínimo','Atendimento','Qualidade do fornecedor','Especificações','Todos os filtros','Filtros ao vivo prontos','Nenhum filtro selecionado','Resultados para','catálogo ao vivo','Ordenar por','Relevância','Vendas mensais','Preço: menor para maior','Preço: maior para menor','Visualização em grade','Dropshipping de uma unidade','Encontrar produtos relacionados','Adicionar aos meus produtos','unidade','unidades','Envio em 48 h','Nota fiscal','Publicar produto','Conversar agora','Histórico de navegação','Continuar explorando','Pesquisas frequentes:','Mais vendidos','Mais produtos','Estoque local','Produtos recomendados','Calculadora de custos','Preços','Integrações','Suporte','Recursos','Blog','Guias de compras','Tutoriais em vídeo','Estudos de caso','Relatórios do setor','Perguntas frequentes','Política de privacidade','Termos e condições','Siga-nos','Aceitamos'],
  'ar-SA': ['بحث','أدخل كلمات المنتج','أدخل كلمات المنتج أو الرابط','مرشحات المنتجات','الفئة','السعر','الحد الأدنى للطلب','التنفيذ','جودة المورد','مواصفات المنتج','كل المرشحات','المرشحات المباشرة جاهزة','لم يتم اختيار مرشحات','نتائج البحث عن','الكتالوج المباشر','ترتيب حسب','الصلة','المبيعات الشهرية','السعر: من الأقل للأعلى','السعر: من الأعلى للأقل','عرض شبكي','دروبشيبينغ لقطعة واحدة','البحث عن منتجات مشابهة','إضافة إلى منتجاتي','قطعة','قطع','شحن خلال 48 ساعة','فاتورة','نشر المنتج','الدردشة الآن','سجل التصفح','متابعة التصفح','عمليات البحث الشائعة:','الأكثر مبيعًا','المزيد من المنتجات','المخزون المحلي','منتجات موصى بها','حاسبة التكلفة','الأسعار','التكاملات','الدعم','الموارد','المدونة','أدلة الشراء','دروس فيديو','دراسات حالة','تقارير القطاع','الأسئلة الشائعة','سياسة الخصوصية','الشروط والأحكام','تابعنا','نقبل'],
  'ja-JP': ['検索','商品キーワードを入力','商品キーワードまたはリンクを入力','商品フィルター','カテゴリー','価格','最小注文数','フルフィルメント','サプライヤー品質','商品仕様','すべてのフィルター','ライブフィルター準備完了','フィルター未選択','検索結果：','ライブカタログ','並び替え','関連度','月間販売数','価格：安い順','価格：高い順','グリッド表示','1点ドロップシッピング','関連商品を探す','マイ商品に追加','点','点','48時間以内に発送','請求書','商品を公開','今すぐチャット','閲覧履歴','さらに見る','よく検索される語句：','ベストセラー','その他の商品','現地在庫','おすすめ商品','コスト計算','料金','連携','サポート','リソース','ブログ','仕入れガイド','動画チュートリアル','事例','業界レポート','よくある質問','プライバシーポリシー','利用規約','フォローする','対応決済'],
  'ko-KR': ['검색','상품 키워드 입력','상품 키워드 또는 링크 입력','상품 필터','카테고리','가격','최소 주문 수량','주문 처리','공급업체 품질','상품 사양','모든 필터','실시간 필터 준비 완료','선택된 필터 없음','검색 결과','실시간 카탈로그','정렬 기준','관련성','월간 판매량','가격: 낮은 순','가격: 높은 순','그리드 보기','1개 드롭시핑','관련 상품 찾기','내 상품에 추가','개','개','48시간 내 발송','인보이스','상품 게시','지금 채팅','검색 기록','계속 둘러보기','자주 검색:','베스트셀러','더 많은 상품','현지 재고','추천 상품','비용 계산기','가격','연동','지원','리소스','블로그','구매 가이드','동영상 튜토리얼','사례 연구','산업 보고서','자주 묻는 질문','개인정보 처리방침','이용약관','팔로우','지원 결제'],
  'ru-RU': ['Поиск','Введите ключевые слова товара','Введите ключевые слова или ссылку','Фильтры товаров','Категория','Цена','Минимальный заказ','Исполнение','Качество поставщика','Характеристики','Все фильтры','Фильтры готовы','Фильтры не выбраны','Результаты для','живой каталог','Сортировать по','Релевантность','Продажи за месяц','Цена: по возрастанию','Цена: по убыванию','Сетка','Дропшиппинг одной единицы','Найти похожие товары','Добавить в мои товары','шт.','шт.','Отправка за 48 ч','Счёт','Опубликовать товар','Чат','История просмотров','Продолжить просмотр','Часто ищут:','Бестселлеры','Больше товаров','Локальный склад','Рекомендуемые товары','Калькулятор стоимости','Цены','Интеграции','Поддержка','Ресурсы','Блог','Руководства по закупкам','Видеоуроки','Кейсы','Отраслевые отчёты','Вопросы и ответы','Политика конфиденциальности','Условия использования','Мы в соцсетях','Мы принимаем'],
}

export const FAST_SITE_TRANSLATIONS: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(rows).map(([locale, values]) => [locale, Object.fromEntries(en.map((key, index) => [key, values[index] || key]))]),
)
