const en = [
  'Search', 'Please enter the product keywords', 'Please enter the product keywords / link',
  'Product filters', 'Category', 'Price', 'MOQ', 'Fulfillment', 'Supplier quality', 'Product specs', 'All filters',
  'Live filters ready', 'No filters selected', 'Results for', 'live catalog', 'Sort by', 'Relevance', 'Monthly sales',
  'Price: low to high', 'Price: high to low', 'Grid view', '1-piece dropship', 'Find related products',
  'Add to my products', 'piece', 'pieces', '48h dispatch', 'Invoice', 'List product', 'Chat now',
  'Browsing history', 'Keep looking for', 'Frequently searched:', 'Best-Sellers Section', 'More Products',
  'Local Stock Zone', 'Recommended Products', 'Cost Calculator', 'Pricing', 'Integrations', 'Support',
  'Resources', 'Blog', 'Procurement Guides', 'Video Tutorials', 'Case Studies', 'Industry Reports', 'FAQ',
  'Privacy Policy', 'Terms & Conditions', 'Find us on', 'We Accept',
]

const rows: Record<string, string[]> = {
  'zh-CN': ['搜索','请输入商品关键词','请输入商品关键词 / 链接','产品筛选','分类','价格','起订量','履约','供应商质量','产品规格','所有筛选','实时筛选就绪','未选择筛选条件','搜索结果','实时目录','排序方式','相关性','月销量','价格：从低到高','价格：从高到低','网格视图','1件代发','查找相关商品','添加到我的商品','件','件','48小时发货','发票','发布商品','立即沟通','浏览历史','继续搜索','热门搜索：','畅销专区','更多产品','本地库存专区','推荐产品','成本计算器','定价','集成','支持','资源','博客','采购指南','视频教程','案例研究','行业报告','常见问题','隐私政策','条款与条件','关注我们','我们接受'],
  'es-ES': ['Buscar','Introduce palabras clave del producto','Introduce palabras clave o enlace','Filtros de productos','Categoría','Precio','Pedido mínimo','Cumplimiento','Calidad del proveedor','Especificaciones','Todos los filtros','Filtros en tiempo real listos','Sin filtros seleccionados','Resultados para','catálogo en tiempo real','Ordenar por','Relevancia','Ventas mensuales','Precio: menor a mayor','Precio: mayor a menor','Vista de cuadrícula','Envío de una unidad','Buscar productos relacionados','Añadir a mis productos','unidad','unidades','Envío en 48 h','Factura','Publicar producto','Chatear ahora','Historial de navegación','Seguir explorando','Búsquedas frecuentes:','Más vendidos','Más productos','Inventario local','Productos recomendados','Calculadora de costes','Precios','Integraciones','Soporte','Recursos','Blog','Guías de compras','Tutoriales en vídeo','Casos de éxito','Informes del sector','Preguntas frecuentes','Política de privacidad','Términos y condiciones','Síguenos','Aceptamos'],
  'fr-FR': ['Rechercher','Saisissez les mots-clés du produit','Saisissez les mots-clés ou le lien','Filtres produits','Catégorie','Prix','MOQ','Exécution','Qualité du fournisseur','Caractéristiques','Tous les filtres','Filtres en direct prêts','Aucun filtre sélectionné','Résultats pour','catalogue en direct','Trier par','Pertinence','Ventes mensuelles','Prix : croissant','Prix : décroissant','Vue grille','Livraison à l’unité','Trouver des produits similaires','Ajouter à mes produits','pièce','pièces','Expédition sous 48 h','Facture','Publier le produit','Discuter maintenant','Historique','Continuer à explorer','Recherches fréquentes :','Meilleures ventes','Plus de produits','Stock local','Produits recommandés','Calculateur de coûts','Tarifs','Intégrations','Assistance','Ressources','Blog','Guides d’achat','Tutoriels vidéo','Études de cas','Rapports sectoriels','FAQ','Politique de confidentialité','Conditions générales','Suivez-nous','Nous acceptons'],
  'de-DE': ['Suchen','Produktbegriffe eingeben','Produktbegriffe oder Link eingeben','Produktfilter','Kategorie','Preis','Mindestbestellmenge','Abwicklung','Lieferantenqualität','Produktspezifikationen','Alle Filter','Live-Filter bereit','Keine Filter ausgewählt','Ergebnisse für','Live-Katalog','Sortieren nach','Relevanz','Monatliche Verkäufe','Preis: aufsteigend','Preis: absteigend','Rasteransicht','Einzelstück-Dropshipping','Ähnliche Produkte finden','Zu meinen Produkten hinzufügen','Stück','Stück','Versand in 48 Std.','Rechnung','Produkt veröffentlichen','Jetzt chatten','Browserverlauf','Weiter entdecken','Häufig gesucht:','Bestseller','Weitere Produkte','Lokaler Bestand','Empfohlene Produkte','Kostenrechner','Preise','Integrationen','Support','Ressourcen','Blog','Einkaufsleitfäden','Video-Tutorials','Fallstudien','Branchenberichte','FAQ','Datenschutzrichtlinie','Geschäftsbedingungen','Folgen Sie uns','Wir akzeptieren'],
  'pt-BR': ['Buscar','Digite palavras-chave do produto','Digite palavras-chave ou link','Filtros de produtos','Categoria','Preço','Pedido mínimo','Atendimento','Qualidade do fornecedor','Especificações','Todos os filtros','Filtros ao vivo prontos','Nenhum filtro selecionado','Resultados para','catálogo ao vivo','Ordenar por','Relevância','Vendas mensais','Preço: menor para maior','Preço: maior para menor','Visualização em grade','Dropshipping de uma unidade','Encontrar produtos relacionados','Adicionar aos meus produtos','unidade','unidades','Envio em 48 h','Nota fiscal','Publicar produto','Conversar agora','Histórico de navegação','Continuar explorando','Pesquisas frequentes:','Mais vendidos','Mais produtos','Estoque local','Produtos recomendados','Calculadora de custos','Preços','Integrações','Suporte','Recursos','Blog','Guias de compras','Tutoriais em vídeo','Estudos de caso','Relatórios do setor','Perguntas frequentes','Política de privacidade','Termos e condições','Siga-nos','Aceitamos'],
  'ar-SA': ['بحث','أدخل كلمات المنتج','أدخل كلمات المنتج أو الرابط','مرشحات المنتجات','الفئة','السعر','الحد الأدنى للطلب','التنفيذ','جودة المورد','مواصفات المنتج','كل المرشحات','المرشحات المباشرة جاهزة','لم يتم اختيار مرشحات','نتائج البحث عن','الكتالوج المباشر','ترتيب حسب','الصلة','المبيعات الشهرية','السعر: من الأقل للأعلى','السعر: من الأعلى للأقل','عرض شبكي','دروبشيبينغ لقطعة واحدة','البحث عن منتجات مشابهة','إضافة إلى منتجاتي','قطعة','قطع','شحن خلال 48 ساعة','فاتورة','نشر المنتج','الدردشة الآن','سجل التصفح','متابعة التصفح','عمليات البحث الشائعة:','الأكثر مبيعًا','المزيد من المنتجات','المخزون المحلي','منتجات موصى بها','حاسبة التكلفة','الأسعار','التكاملات','الدعم','الموارد','المدونة','أدلة الشراء','دروس فيديو','دراسات حالة','تقارير القطاع','الأسئلة الشائعة','سياسة الخصوصية','الشروط والأحكام','تابعنا','نقبل'],
  'ja-JP': ['検索','商品キーワードを入力','商品キーワードまたはリンクを入力','商品フィルター','カテゴリー','価格','最小注文数','フルフィルメント','サプライヤー品質','商品仕様','すべてのフィルター','ライブフィルター準備完了','フィルター未選択','検索結果：','ライブカタログ','並び替え','関連度','月間販売数','価格：安い順','価格：高い順','グリッド表示','1点ドロップシッピング','関連商品を探す','マイ商品に追加','点','点','48時間以内に発送','請求書','商品を公開','今すぐチャット','閲覧履歴','さらに見る','よく検索される語句：','ベストセラー','その他の商品','現地在庫','おすすめ商品','コスト計算','料金','連携','サポート','リソース','ブログ','仕入れガイド','動画チュートリアル','事例','業界レポート','よくある質問','プライバシーポリシー','利用規約','フォローする','対応決済'],
  'ko-KR': ['검색','상품 키워드 입력','상품 키워드 또는 링크 입력','상품 필터','카테고리','가격','최소 주문 수량','주문 처리','공급업체 품질','상품 사양','모든 필터','실시간 필터 준비 완료','선택된 필터 없음','검색 결과','실시간 카탈로그','정렬 기준','관련성','월간 판매량','가격: 낮은 순','가격: 높은 순','그리드 보기','1개 드롭시핑','관련 상품 찾기','내 상품에 추가','개','개','48시간 내 발송','인보이스','상품 게시','지금 채팅','검색 기록','계속 둘러보기','자주 검색:','베스트셀러','더 많은 상품','현지 재고','추천 상품','비용 계산기','가격','연동','지원','리소스','블로그','구매 가이드','동영상 튜토리얼','사례 연구','산업 보고서','자주 묻는 질문','개인정보 처리방침','이용약관','팔로우','지원 결제'],
  'ru-RU': ['Поиск','Введите ключевые слова товара','Введите ключевые слова или ссылку','Фильтры товаров','Категория','Цена','Минимальный заказ','Исполнение','Качество поставщика','Характеристики','Все фильтры','Фильтры готовы','Фильтры не выбраны','Результаты для','живой каталог','Сортировать по','Релевантность','Продажи за месяц','Цена: по возрастанию','Цена: по убыванию','Сетка','Дропшиппинг одной единицы','Найти похожие товары','Добавить в мои товары','шт.','шт.','Отправка за 48 ч','Счёт','Опубликовать товар','Чат','История просмотров','Продолжить просмотр','Часто ищут:','Бестселлеры','Больше товаров','Локальный склад','Рекомендуемые товары','Калькулятор стоимости','Цены','Интеграции','Поддержка','Ресурсы','Блог','Руководства по закупкам','Видеоуроки','Кейсы','Отраслевые отчёты','Вопросы и ответы','Политика конфиденциальности','Условия использования','Мы в соцсетях','Мы принимаем'],
}

const productDetailEn = [
  'Description', '1688 Original Link', 'Alibaba Original Link', 'Source goods ex-factory price',
  'Prices may vary with promotions or quantity, and are final as displayed at checkout.',
  'Customer Rating:', 'Sold:', 'Repurchase Rate:', 'Color', 'Size', 'Qty', 'Count', 'Quantity',
  'Shipping Country', 'Available:', 'Product Sourcing - CoDropshipping Warehouse',
  'Pay product cost first, shipping fee charged later', 'Shipping Destination:',
  'After selecting the product, the shipping fee will be automatically calculated based on the volume and weight of the product.',
  'Shipping calculated automatically', 'Shipping calculator', 'List to my store', 'AI-assisted by default',
  'Add to cart', 'Manual listing', 'Order now', 'Adding...', 'Preparing...',
  'Taxes and related import fees will be calculated at checkout.', 'Chat Now', 'The product has expired', 'Please log', 'Success!',
]

const productDetailRows: Record<string, string[]> = {
  'zh-CN': ['描述','1688原始链接','Alibaba原始链接','货源出厂价','价格可能因促销或数量而异，最终以结账时显示为准。','客户评分：','已售：','复购率：','颜色','尺寸','数量','数量','数量','配送国家','可用库存：','商品采购 - CoDropshipping仓库','先付商品成本，运费稍后收取','收货目的地：','选择商品后，系统将根据商品体积和重量自动计算运费。','自动计算运费','运费计算器','刊登到我的店铺','默认使用AI辅助','加入购物车','手动刊登','立即下单','正在加入...','正在准备...','税费及相关进口费用将在结账时计算。','立即沟通','商品已失效','请先登录','成功！'],
  'es-ES': ['Descripción','Enlace original de 1688','Enlace original de Alibaba','Precio de fábrica del producto','Los precios pueden variar según la promoción o la cantidad; prevalece el importe mostrado al pagar.','Valoración del cliente:','Vendidos:','Tasa de recompra:','Color','Tamaño','Cant.','Cantidad','Cantidad','País de envío','Disponible:','Compra del producto - Almacén de CoDropshipping','Paga primero el producto; el envío se cobra después','Destino del envío:','Tras seleccionar el producto, el envío se calculará automáticamente según su volumen y peso.','Envío calculado automáticamente','Calculadora de envíos','Publicar en mi tienda','Asistencia de IA por defecto','Añadir al carrito','Publicación manual','Comprar ahora','Añadiendo...','Preparando...','Los impuestos y tasas de importación se calcularán al pagar.','Chatear ahora','El producto ha caducado','Inicia sesión','¡Éxito!'],
  'fr-FR': ['Description','Lien 1688 d’origine','Lien Alibaba d’origine','Prix départ usine','Les prix peuvent varier selon les promotions ou la quantité ; le montant affiché au paiement fait foi.','Avis clients :','Vendus :','Taux de rachat :','Couleur','Taille','Qté','Nombre','Quantité','Pays de livraison','Disponible :','Achat du produit - Entrepôt CoDropshipping','Payez d’abord le produit ; les frais de livraison seront facturés ensuite','Destination :','Après sélection, les frais de livraison sont calculés automatiquement selon le volume et le poids.','Livraison calculée automatiquement','Calculateur de livraison','Publier dans ma boutique','Assistance IA par défaut','Ajouter au panier','Publication manuelle','Commander','Ajout...','Préparation...','Les taxes et frais d’importation seront calculés au paiement.','Discuter maintenant','Le produit a expiré','Connectez-vous','Succès !'],
  'de-DE': ['Beschreibung','1688-Original-Link','Alibaba-Original-Link','Werkspreis','Preise können je nach Aktion oder Menge variieren; maßgeblich ist der Betrag an der Kasse.','Kundenbewertung:','Verkauft:','Wiederkaufsrate:','Farbe','Größe','Menge','Anzahl','Menge','Versandland','Verfügbar:','Produktbeschaffung - CoDropshipping-Lager','Zuerst Produktkosten zahlen; Versand wird später berechnet','Versandziel:','Nach der Produktauswahl werden die Versandkosten anhand von Volumen und Gewicht automatisch berechnet.','Versand wird automatisch berechnet','Versandrechner','In meinem Shop listen','Standardmäßig KI-unterstützt','In den Warenkorb','Manuell listen','Jetzt bestellen','Wird hinzugefügt...','Wird vorbereitet...','Steuern und Einfuhrgebühren werden an der Kasse berechnet.','Jetzt chatten','Das Produkt ist abgelaufen','Bitte anmelden','Erfolgreich!'],
  'pt-BR': ['Descrição','Link original da 1688','Link original da Alibaba','Preço de fábrica','Os preços podem variar conforme a promoção ou quantidade; vale o total exibido no checkout.','Avaliação dos clientes:','Vendidos:','Taxa de recompra:','Cor','Tamanho','Qtd.','Contagem','Quantidade','País de envio','Disponível:','Compra do produto - Armazém CoDropshipping','Pague primeiro o produto; o frete será cobrado depois','Destino do envio:','Após selecionar o produto, o frete será calculado automaticamente pelo volume e peso.','Frete calculado automaticamente','Calculadora de frete','Publicar na minha loja','Assistência de IA por padrão','Adicionar ao carrinho','Publicação manual','Comprar agora','Adicionando...','Preparando...','Impostos e taxas de importação serão calculados no checkout.','Conversar agora','O produto expirou','Faça login','Sucesso!'],
  'ar-SA': ['الوصف','رابط 1688 الأصلي','رابط Alibaba الأصلي','سعر المصنع','قد تختلف الأسعار حسب العرض أو الكمية، ويُعتمد السعر الظاهر عند الدفع.','تقييم العملاء:','المبيعات:','معدل إعادة الشراء:','اللون','المقاس','الكمية','العدد','الكمية','بلد الشحن','المتاح:','توريد المنتج - مستودع CoDropshipping','ادفع تكلفة المنتج أولاً وتُحسب رسوم الشحن لاحقاً','وجهة الشحن:','بعد اختيار المنتج تُحسب رسوم الشحن تلقائياً حسب الحجم والوزن.','يُحسب الشحن تلقائياً','حاسبة الشحن','إدراج في متجري','مساعدة الذكاء الاصطناعي افتراضياً','إضافة إلى السلة','إدراج يدوي','اطلب الآن','جارٍ الإضافة...','جارٍ التحضير...','تُحسب الضرائب ورسوم الاستيراد عند الدفع.','الدردشة الآن','انتهت صلاحية المنتج','يرجى تسجيل الدخول','تم بنجاح!'],
  'ja-JP': ['説明','1688元リンク','Alibaba元リンク','工場出荷価格','価格はキャンペーンや数量により変動する場合があり、決済画面の表示が最終価格です。','顧客評価：','販売数：','再購入率：','カラー','サイズ','数量','個数','数量','配送先の国','在庫：','商品仕入れ - CoDropshipping倉庫','商品代金を先に支払い、送料は後で請求されます','配送先：','商品選択後、体積と重量に基づいて送料が自動計算されます。','送料を自動計算','送料計算ツール','自分のストアに出品','AIアシストが標準','カートに追加','手動出品','今すぐ注文','追加中...','準備中...','税金および輸入関連費用は決済時に計算されます。','今すぐチャット','商品は期限切れです','ログインしてください','成功しました！'],
  'ko-KR': ['설명','1688 원본 링크','Alibaba 원본 링크','공장 출고가','가격은 프로모션이나 수량에 따라 달라질 수 있으며 결제 화면의 금액이 최종 가격입니다.','고객 평점:','판매량:','재구매율:','색상','크기','수량','개수','수량','배송 국가','재고:','상품 소싱 - CoDropshipping 창고','상품 대금을 먼저 결제하고 배송비는 나중에 청구됩니다','배송지:','상품 선택 후 부피와 무게에 따라 배송비가 자동 계산됩니다.','배송비 자동 계산','배송비 계산기','내 스토어에 등록','기본 AI 지원','장바구니에 추가','수동 등록','지금 주문','추가 중...','준비 중...','세금 및 수입 관련 비용은 결제 시 계산됩니다.','지금 채팅','상품이 만료되었습니다','로그인해 주세요','성공!'],
  'ru-RU': ['Описание','Оригинальная ссылка 1688','Оригинальная ссылка Alibaba','Заводская цена','Цена может меняться из-за акций или количества; окончательная сумма указана при оформлении.','Оценка покупателей:','Продано:','Доля повторных покупок:','Цвет','Размер','Кол-во','Количество','Количество','Страна доставки','Доступно:','Закупка товара — склад CoDropshipping','Сначала оплачивается товар, доставка списывается позже','Направление доставки:','После выбора товара стоимость доставки рассчитывается автоматически по объёму и весу.','Автоматический расчёт доставки','Калькулятор доставки','Добавить в мой магазин','ИИ-помощь по умолчанию','Добавить в корзину','Ручное размещение','Заказать сейчас','Добавление...','Подготовка...','Налоги и импортные сборы рассчитываются при оформлении.','Чат','Срок действия товара истёк','Войдите в аккаунт','Готово!'],
}

export const FAST_SITE_TRANSLATIONS: Record<string, Record<string, string>> = Object.fromEntries(
  Object.entries(rows).map(([locale, values]) => {
    const detailValues = productDetailRows[locale] || []
    return [locale, Object.fromEntries([
      ...en.map((key, index) => [key, values[index] || key]),
      ...productDetailEn.map((key, index) => [key, detailValues[index] || key]),
    ])]
  }),
)
