export const cartMessages = {
  'en-US': {
    'cart.eyebrow': 'Sourcing cart', 'cart.title': 'Review products before ordering', 'cart.subtitle': 'Confirm variants, quantities and estimated product cost before creating a sourcing order.', 'cart.continueShopping': 'Continue sourcing', 'cart.searchPlaceholder': 'Search products in your cart', 'cart.search': 'Search', 'cart.clear': 'Clear', 'cart.items': 'Products', 'cart.units': 'Units', 'cart.selected': 'Selected', 'cart.total': 'Estimated product cost', 'cart.product': 'Product', 'cart.quantity': 'Quantity', 'cart.price': 'Unit price', 'cart.subtotal': 'Subtotal', 'cart.selectAll': 'Select all', 'cart.removeSelected': 'Remove selected', 'cart.checkout': 'Continue to order', 'cart.checkoutHint': 'Shipping is calculated after the destination and delivery method are confirmed.', 'cart.emptyTitle': 'Your sourcing cart is empty', 'cart.emptyCopy': 'Choose a product from CoD and add the variants you want to order.', 'cart.browse': 'Browse products', 'cart.loading': 'Loading your cart...', 'cart.errorTitle': 'Cart could not be loaded', 'cart.errorCopy': 'The cart service did not respond.', 'cart.retry': 'Try again', 'cart.selectProduct': 'Select {value}', 'cart.selectVariant': 'Select {value}', 'cart.deleteTitle': 'Remove selected items?', 'cart.deleteCopy': 'The selected variants will be removed from your sourcing cart.', 'cart.cancel': 'Cancel', 'cart.confirmDelete': 'Remove items', 'cart.deleting': 'Removing...', 'cart.saving': 'Saving...', 'cart.selectFirst': 'Select at least one variant to continue.',
  },
  'zh-CN': {
    'cart.eyebrow': '采购购物车', 'cart.title': '下单前核对商品', 'cart.subtitle': '创建采购订单前，确认规格、数量和预估商品费用。', 'cart.continueShopping': '继续选品', 'cart.searchPlaceholder': '搜索购物车商品', 'cart.search': '搜索', 'cart.clear': '清除', 'cart.items': '商品', 'cart.units': '件数', 'cart.selected': '已选', 'cart.total': '预估商品费用', 'cart.product': '商品', 'cart.quantity': '数量', 'cart.price': '单价', 'cart.subtotal': '小计', 'cart.selectAll': '全选', 'cart.removeSelected': '移除所选', 'cart.checkout': '继续下单', 'cart.checkoutHint': '确认收货地和物流方式后计算运费。', 'cart.emptyTitle': '采购购物车还是空的', 'cart.emptyCopy': '从 CoD 选择商品，并加入需要采购的规格。', 'cart.browse': '浏览商品', 'cart.loading': '正在加载购物车...', 'cart.errorTitle': '无法加载购物车', 'cart.errorCopy': '购物车服务没有响应。', 'cart.retry': '重试', 'cart.selectProduct': '选择 {value}', 'cart.selectVariant': '选择 {value}', 'cart.deleteTitle': '移除所选商品？', 'cart.deleteCopy': '所选规格将从采购购物车中移除。', 'cart.cancel': '取消', 'cart.confirmDelete': '移除商品', 'cart.deleting': '正在移除...', 'cart.saving': '正在保存...', 'cart.selectFirst': '请至少选择一个规格后继续。',
  },
  'es-ES': {
    'cart.eyebrow':'Carrito de abastecimiento','cart.title':'Revisa los productos antes de pedir','cart.subtitle':'Confirma variantes, cantidades y coste estimado antes de crear el pedido.','cart.continueShopping':'Seguir buscando','cart.searchPlaceholder':'Buscar en el carrito','cart.search':'Buscar','cart.clear':'Limpiar','cart.items':'Productos','cart.units':'Unidades','cart.selected':'Seleccionado','cart.total':'Coste estimado','cart.product':'Producto','cart.quantity':'Cantidad','cart.price':'Precio unitario','cart.subtotal':'Subtotal','cart.selectAll':'Seleccionar todo','cart.removeSelected':'Eliminar selección','cart.checkout':'Continuar al pedido','cart.checkoutHint':'El envío se calcula tras confirmar destino y método.','cart.emptyTitle':'Tu carrito está vacío','cart.emptyCopy':'Elige productos CoD y añade las variantes que quieras pedir.','cart.browse':'Explorar productos','cart.loading':'Cargando carrito...','cart.errorTitle':'No se pudo cargar el carrito','cart.errorCopy':'El servicio no respondió.','cart.retry':'Reintentar','cart.selectProduct':'Seleccionar {value}','cart.selectVariant':'Seleccionar {value}','cart.deleteTitle':'¿Eliminar los artículos seleccionados?','cart.deleteCopy':'Las variantes seleccionadas se eliminarán del carrito.','cart.cancel':'Cancelar','cart.confirmDelete':'Eliminar artículos','cart.deleting':'Eliminando...','cart.saving':'Guardando...','cart.selectFirst':'Selecciona al menos una variante para continuar.',
  },
  'fr-FR': {
    'cart.eyebrow':'Panier sourcing','cart.title':'Vérifiez les produits avant de commander','cart.subtitle':'Confirmez variantes, quantités et coût estimé avant de créer la commande.','cart.continueShopping':'Continuer le sourcing','cart.searchPlaceholder':'Rechercher dans le panier','cart.search':'Rechercher','cart.clear':'Effacer','cart.items':'Produits','cart.units':'Unités','cart.selected':'Sélection','cart.total':'Coût estimé','cart.product':'Produit','cart.quantity':'Quantité','cart.price':'Prix unitaire','cart.subtotal':'Sous-total','cart.selectAll':'Tout sélectionner','cart.removeSelected':'Retirer la sélection','cart.checkout':'Continuer la commande','cart.checkoutHint':'La livraison est calculée après confirmation de la destination et du mode.','cart.emptyTitle':'Votre panier est vide','cart.emptyCopy':'Choisissez des produits CoD et ajoutez les variantes à commander.','cart.browse':'Parcourir les produits','cart.loading':'Chargement du panier...','cart.errorTitle':'Impossible de charger le panier','cart.errorCopy':'Le service du panier ne répond pas.','cart.retry':'Réessayer','cart.selectProduct':'Sélectionner {value}','cart.selectVariant':'Sélectionner {value}','cart.deleteTitle':'Retirer les articles sélectionnés ?','cart.deleteCopy':'Les variantes sélectionnées seront retirées du panier.','cart.cancel':'Annuler','cart.confirmDelete':'Retirer les articles','cart.deleting':'Suppression...','cart.saving':'Enregistrement...','cart.selectFirst':'Sélectionnez au moins une variante pour continuer.',
  },
  'de-DE': {
    'cart.eyebrow':'Beschaffungswarenkorb','cart.title':'Produkte vor der Bestellung prüfen','cart.subtitle':'Varianten, Mengen und geschätzte Kosten vor der Bestellung bestätigen.','cart.continueShopping':'Weiter suchen','cart.searchPlaceholder':'Warenkorb durchsuchen','cart.search':'Suchen','cart.clear':'Löschen','cart.items':'Produkte','cart.units':'Einheiten','cart.selected':'Ausgewählt','cart.total':'Geschätzte Kosten','cart.product':'Produkt','cart.quantity':'Menge','cart.price':'Stückpreis','cart.subtotal':'Zwischensumme','cart.selectAll':'Alle auswählen','cart.removeSelected':'Auswahl entfernen','cart.checkout':'Zur Bestellung','cart.checkoutHint':'Der Versand wird nach Ziel und Versandart berechnet.','cart.emptyTitle':'Ihr Warenkorb ist leer','cart.emptyCopy':'Wählen Sie CoD-Produkte und die gewünschten Varianten.','cart.browse':'Produkte ansehen','cart.loading':'Warenkorb wird geladen...','cart.errorTitle':'Warenkorb nicht verfügbar','cart.errorCopy':'Der Warenkorbdienst antwortet nicht.','cart.retry':'Erneut versuchen','cart.selectProduct':'{value} auswählen','cart.selectVariant':'{value} auswählen','cart.deleteTitle':'Ausgewählte Artikel entfernen?','cart.deleteCopy':'Die ausgewählten Varianten werden entfernt.','cart.cancel':'Abbrechen','cart.confirmDelete':'Artikel entfernen','cart.deleting':'Wird entfernt...','cart.saving':'Wird gespeichert...','cart.selectFirst':'Wählen Sie mindestens eine Variante aus.',
  },
  'pt-BR': {
    'cart.eyebrow':'Carrinho de sourcing','cart.title':'Revise os produtos antes do pedido','cart.subtitle':'Confirme variações, quantidades e custo estimado antes de criar o pedido.','cart.continueShopping':'Continuar buscando','cart.searchPlaceholder':'Buscar no carrinho','cart.search':'Buscar','cart.clear':'Limpar','cart.items':'Produtos','cart.units':'Unidades','cart.selected':'Selecionado','cart.total':'Custo estimado','cart.product':'Produto','cart.quantity':'Quantidade','cart.price':'Preço unitário','cart.subtotal':'Subtotal','cart.selectAll':'Selecionar tudo','cart.removeSelected':'Remover seleção','cart.checkout':'Continuar para o pedido','cart.checkoutHint':'O frete é calculado após confirmar destino e método.','cart.emptyTitle':'Seu carrinho está vazio','cart.emptyCopy':'Escolha produtos CoD e adicione as variações desejadas.','cart.browse':'Ver produtos','cart.loading':'Carregando carrinho...','cart.errorTitle':'Não foi possível carregar','cart.errorCopy':'O serviço do carrinho não respondeu.','cart.retry':'Tentar novamente','cart.selectProduct':'Selecionar {value}','cart.selectVariant':'Selecionar {value}','cart.deleteTitle':'Remover itens selecionados?','cart.deleteCopy':'As variações selecionadas serão removidas.','cart.cancel':'Cancelar','cart.confirmDelete':'Remover itens','cart.deleting':'Removendo...','cart.saving':'Salvando...','cart.selectFirst':'Selecione pelo menos uma variação para continuar.',
  },
  'ar-SA': {
    'cart.eyebrow':'سلة التوريد','cart.title':'راجع المنتجات قبل الطلب','cart.subtitle':'أكد الخيارات والكميات والتكلفة التقديرية.','cart.continueShopping':'متابعة التوريد','cart.searchPlaceholder':'البحث في السلة','cart.search':'بحث','cart.clear':'مسح','cart.items':'المنتجات','cart.units':'الوحدات','cart.selected':'المحدد','cart.total':'التكلفة التقديرية','cart.product':'المنتج','cart.quantity':'الكمية','cart.price':'سعر الوحدة','cart.subtotal':'المجموع الفرعي','cart.selectAll':'تحديد الكل','cart.removeSelected':'إزالة المحدد','cart.checkout':'متابعة الطلب','cart.checkoutHint':'يحسب الشحن بعد تأكيد الوجهة والطريقة.','cart.emptyTitle':'سلة التوريد فارغة','cart.emptyCopy':'اختر منتجات CoD وأضف الخيارات المطلوبة.','cart.browse':'تصفح المنتجات','cart.loading':'جارٍ تحميل السلة...','cart.errorTitle':'تعذر تحميل السلة','cart.errorCopy':'خدمة السلة لا تستجيب.','cart.retry':'إعادة المحاولة','cart.selectProduct':'تحديد {value}','cart.selectVariant':'تحديد {value}','cart.deleteTitle':'إزالة العناصر المحددة؟','cart.deleteCopy':'ستتم إزالة الخيارات المحددة.','cart.cancel':'إلغاء','cart.confirmDelete':'إزالة العناصر','cart.deleting':'جارٍ الإزالة...','cart.saving':'جارٍ الحفظ...','cart.selectFirst':'حدد خيارًا واحدًا على الأقل.',
  },
  'ja-JP': {
    'cart.eyebrow':'仕入れカート','cart.title':'注文前に商品を確認','cart.subtitle':'仕入れ注文作成前にバリエーション、数量、概算商品代を確認します。','cart.continueShopping':'商品探しを続ける','cart.searchPlaceholder':'カートを検索','cart.search':'検索','cart.clear':'クリア','cart.items':'商品','cart.units':'点数','cart.selected':'選択済み','cart.total':'概算商品代','cart.product':'商品','cart.quantity':'数量','cart.price':'単価','cart.subtotal':'小計','cart.selectAll':'すべて選択','cart.removeSelected':'選択項目を削除','cart.checkout':'注文へ進む','cart.checkoutHint':'送料は届先と配送方法の確定後に計算されます。','cart.emptyTitle':'カートは空です','cart.emptyCopy':'CoD で商品を選び、必要なバリエーションを追加してください。','cart.browse':'商品を見る','cart.loading':'カートを読み込み中...','cart.errorTitle':'カートを読み込めません','cart.errorCopy':'カートサービスが応答しません。','cart.retry':'再試行','cart.selectProduct':'{value} を選択','cart.selectVariant':'{value} を選択','cart.deleteTitle':'選択項目を削除しますか？','cart.deleteCopy':'選択したバリエーションがカートから削除されます。','cart.cancel':'キャンセル','cart.confirmDelete':'削除','cart.deleting':'削除中...','cart.saving':'保存中...','cart.selectFirst':'少なくとも1つ選択してください。',
  },
  'ko-KR': {
    'cart.eyebrow':'소싱 장바구니','cart.title':'주문 전 상품 확인','cart.subtitle':'소싱 주문 생성 전 옵션, 수량, 예상 상품 비용을 확인하세요.','cart.continueShopping':'소싱 계속','cart.searchPlaceholder':'장바구니 검색','cart.search':'검색','cart.clear':'지우기','cart.items':'상품','cart.units':'수량','cart.selected':'선택','cart.total':'예상 상품 비용','cart.product':'상품','cart.quantity':'수량','cart.price':'단가','cart.subtotal':'소계','cart.selectAll':'전체 선택','cart.removeSelected':'선택 삭제','cart.checkout':'주문 계속','cart.checkoutHint':'목적지와 배송 방식 확정 후 배송비가 계산됩니다.','cart.emptyTitle':'장바구니가 비어 있습니다','cart.emptyCopy':'CoD 상품과 주문할 옵션을 추가하세요.','cart.browse':'상품 보기','cart.loading':'장바구니 로드 중...','cart.errorTitle':'장바구니를 불러오지 못했습니다','cart.errorCopy':'장바구니 서비스가 응답하지 않습니다.','cart.retry':'다시 시도','cart.selectProduct':'{value} 선택','cart.selectVariant':'{value} 선택','cart.deleteTitle':'선택한 항목을 삭제할까요?','cart.deleteCopy':'선택한 옵션이 장바구니에서 삭제됩니다.','cart.cancel':'취소','cart.confirmDelete':'항목 삭제','cart.deleting':'삭제 중...','cart.saving':'저장 중...','cart.selectFirst':'계속하려면 옵션을 하나 이상 선택하세요.',
  },
  'ru-RU': {
    'cart.eyebrow':'Корзина закупок','cart.title':'Проверьте товары перед заказом','cart.subtitle':'Подтвердите варианты, количество и оценочную стоимость.','cart.continueShopping':'Продолжить поиск','cart.searchPlaceholder':'Поиск в корзине','cart.search':'Поиск','cart.clear':'Очистить','cart.items':'Товары','cart.units':'Единицы','cart.selected':'Выбрано','cart.total':'Оценочная стоимость','cart.product':'Товар','cart.quantity':'Количество','cart.price':'Цена','cart.subtotal':'Подытог','cart.selectAll':'Выбрать всё','cart.removeSelected':'Удалить выбранное','cart.checkout':'Перейти к заказу','cart.checkoutHint':'Доставка рассчитывается после выбора адреса и способа.','cart.emptyTitle':'Корзина пуста','cart.emptyCopy':'Выберите товары CoD и добавьте нужные варианты.','cart.browse':'Смотреть товары','cart.loading':'Загрузка корзины...','cart.errorTitle':'Не удалось загрузить корзину','cart.errorCopy':'Сервис корзины не ответил.','cart.retry':'Повторить','cart.selectProduct':'Выбрать {value}','cart.selectVariant':'Выбрать {value}','cart.deleteTitle':'Удалить выбранные позиции?','cart.deleteCopy':'Выбранные варианты будут удалены.','cart.cancel':'Отмена','cart.confirmDelete':'Удалить','cart.deleting':'Удаление...','cart.saving':'Сохранение...','cart.selectFirst':'Выберите минимум один вариант.',
  },
}
