const en = {
  'orders.kicker': 'Order control', 'orders.title': 'Store orders', 'orders.subtitle': 'Review real orders from every connected store and move the right work into fulfillment.',
  'orders.summary': 'Order summary', 'orders.currentQueue': 'Orders in this queue', 'orders.connectedStores': 'Connected stores', 'orders.visibleOrders': 'Visible on this page', 'orders.pageOf': 'Page {page} of {pages}',
  'orders.nextAction': 'Next action', 'orders.nextActionCopy': 'Work from the selected queue', 'orders.reviewOrders': 'Review orders', 'orders.manageQueue': 'Manage queue',
  'orders.pending': 'Pending', 'orders.picking': 'Order picking', 'orders.awaitingPayment': 'Awaiting payment', 'orders.paid': 'Paid, not shipped', 'orders.dispatched': 'Dispatched', 'orders.completed': 'Completed', 'orders.cancelled': 'Cancelled', 'orders.statusFilter': 'Order status',
  'orders.searchLabel': 'Search orders', 'orders.searchPlaceholder': 'Order number or product title', 'orders.storeLabel': 'Store', 'orders.allStores': 'All connected stores', 'orders.reset': 'Reset',
  'orders.errorTitle': 'Orders could not be loaded', 'orders.errorFallback': 'The store order service did not respond.', 'orders.emptyTitle': 'No orders in this queue', 'orders.emptyCopy': 'Sync a connected store to import its latest orders.', 'orders.emptyFilteredCopy': 'No orders match the current search and store filters.', 'orders.clearFilters': 'Clear filters',
  'orders.order': 'Order', 'orders.items': 'Items', 'orders.store': 'Store', 'orders.customer': 'Customer', 'orders.cost': 'Cost', 'orders.shipping': 'Shipping', 'orders.created': 'Created', 'orders.action': 'Action', 'orders.review': 'Review',
  'orders.itemCount': '{value} item(s)', 'orders.productCost': 'Product cost', 'orders.shippingCost': 'Shipping cost', 'orders.unnamedItem': 'Store product', 'orders.shopify': 'Shopify', 'orders.destination': 'Destination', 'orders.openFulfillment': 'Open fulfillment',
  'orders.resultCount': '{value} orders', 'orders.previous': 'Previous page', 'orders.next': 'Next page',
  'orders.sync': 'Sync store orders', 'orders.syncing': 'Syncing orders...', 'orders.syncLabel': 'Store sync', 'orders.syncTitle': 'Import the latest store orders', 'orders.syncCopy': 'Choose one authorized store. CoD will request its latest orders without changing them in Shopify.', 'orders.confirmSync': 'Sync orders', 'orders.syncError': 'Orders could not be synchronized.',
}

const zh = {
  'orders.kicker': '订单控制中心', 'orders.title': '店铺订单', 'orders.subtitle': '在统一队列中查看所有已连接店铺的真实订单，并将需要处理的订单进入履约流程。',
  'orders.summary': '订单摘要', 'orders.currentQueue': '当前队列订单', 'orders.connectedStores': '已连接店铺', 'orders.visibleOrders': '本页显示订单', 'orders.pageOf': '第 {page} / {pages} 页',
  'orders.nextAction': '下一步操作', 'orders.nextActionCopy': '按照当前队列继续处理', 'orders.reviewOrders': '审核订单', 'orders.manageQueue': '处理队列',
  'orders.pending': '待处理', 'orders.picking': '拣货中', 'orders.awaitingPayment': '等待付款', 'orders.paid': '已付款待发货', 'orders.dispatched': '已发货', 'orders.completed': '已完成', 'orders.cancelled': '已取消', 'orders.statusFilter': '订单状态',
  'orders.searchLabel': '搜索订单', 'orders.searchPlaceholder': '输入订单号或商品标题', 'orders.storeLabel': '店铺', 'orders.allStores': '全部已连接店铺', 'orders.reset': '重置',
  'orders.errorTitle': '订单加载失败', 'orders.errorFallback': '店铺订单服务没有响应。', 'orders.emptyTitle': '当前队列没有订单', 'orders.emptyCopy': '同步已连接店铺，即可导入最新订单。', 'orders.emptyFilteredCopy': '没有符合当前搜索和店铺筛选条件的订单。', 'orders.clearFilters': '清除筛选',
  'orders.order': '订单', 'orders.items': '商品', 'orders.store': '店铺', 'orders.customer': '客户', 'orders.cost': '成本', 'orders.shipping': '物流', 'orders.created': '创建时间', 'orders.action': '操作', 'orders.review': '查看',
  'orders.itemCount': '共 {value} 件', 'orders.productCost': '商品成本', 'orders.shippingCost': '物流成本', 'orders.unnamedItem': '店铺商品', 'orders.shopify': 'Shopify', 'orders.destination': '收货地区', 'orders.openFulfillment': '进入履约中心',
  'orders.resultCount': '共 {value} 个订单', 'orders.previous': '上一页', 'orders.next': '下一页',
  'orders.sync': '同步店铺订单', 'orders.syncing': '正在同步订单...', 'orders.syncLabel': '店铺同步', 'orders.syncTitle': '导入店铺最新订单', 'orders.syncCopy': '选择一个已授权店铺。CoD 只读取最新订单，不会修改 Shopify 中的订单。', 'orders.confirmSync': '开始同步', 'orders.syncError': '订单同步失败。',
}

const es = {
  'orders.kicker': 'Control de pedidos', 'orders.title': 'Pedidos de tiendas', 'orders.subtitle': 'Revisa pedidos reales de todas las tiendas conectadas y envía el trabajo correcto a preparación.',
  'orders.summary': 'Resumen de pedidos', 'orders.currentQueue': 'Pedidos en esta cola', 'orders.connectedStores': 'Tiendas conectadas', 'orders.visibleOrders': 'Visibles en esta página', 'orders.pageOf': 'Página {page} de {pages}', 'orders.nextAction': 'Siguiente acción', 'orders.nextActionCopy': 'Trabaja desde la cola seleccionada', 'orders.reviewOrders': 'Revisar pedidos', 'orders.manageQueue': 'Gestionar cola',
  'orders.pending': 'Pendientes', 'orders.picking': 'Preparando', 'orders.awaitingPayment': 'Esperando pago', 'orders.paid': 'Pagados, sin enviar', 'orders.dispatched': 'Enviados', 'orders.completed': 'Completados', 'orders.cancelled': 'Cancelados', 'orders.statusFilter': 'Estado del pedido',
  'orders.searchLabel': 'Buscar pedidos', 'orders.searchPlaceholder': 'Número de pedido o título', 'orders.storeLabel': 'Tienda', 'orders.allStores': 'Todas las tiendas conectadas', 'orders.reset': 'Restablecer', 'orders.errorTitle': 'No se pudieron cargar los pedidos', 'orders.errorFallback': 'El servicio de pedidos no respondió.', 'orders.emptyTitle': 'No hay pedidos en esta cola', 'orders.emptyCopy': 'Sincroniza una tienda conectada para importar los pedidos recientes.', 'orders.emptyFilteredCopy': 'Ningún pedido coincide con los filtros.', 'orders.clearFilters': 'Borrar filtros',
  'orders.order': 'Pedido', 'orders.items': 'Artículos', 'orders.store': 'Tienda', 'orders.customer': 'Cliente', 'orders.cost': 'Costo', 'orders.shipping': 'Envío', 'orders.created': 'Creado', 'orders.action': 'Acción', 'orders.review': 'Revisar', 'orders.itemCount': '{value} artículo(s)', 'orders.productCost': 'Costo del producto', 'orders.shippingCost': 'Costo de envío', 'orders.unnamedItem': 'Producto de tienda', 'orders.shopify': 'Shopify', 'orders.destination': 'Destino', 'orders.openFulfillment': 'Abrir preparación', 'orders.resultCount': '{value} pedidos', 'orders.previous': 'Página anterior', 'orders.next': 'Página siguiente',
  'orders.sync': 'Sincronizar pedidos', 'orders.syncing': 'Sincronizando...', 'orders.syncLabel': 'Sincronización', 'orders.syncTitle': 'Importar los pedidos recientes', 'orders.syncCopy': 'Elige una tienda autorizada. CoD solicitará sus pedidos sin modificarlos en Shopify.', 'orders.confirmSync': 'Sincronizar', 'orders.syncError': 'No se pudieron sincronizar los pedidos.',
}

const fr = {
  'orders.kicker': 'Contrôle des commandes', 'orders.title': 'Commandes boutiques', 'orders.subtitle': 'Consultez les commandes réelles de chaque boutique et envoyez les bonnes tâches vers le traitement.',
  'orders.summary': 'Résumé des commandes', 'orders.currentQueue': 'Commandes dans cette file', 'orders.connectedStores': 'Boutiques connectées', 'orders.visibleOrders': 'Visibles sur cette page', 'orders.pageOf': 'Page {page} sur {pages}', 'orders.nextAction': 'Action suivante', 'orders.nextActionCopy': 'Travaillez depuis la file sélectionnée', 'orders.reviewOrders': 'Vérifier les commandes', 'orders.manageQueue': 'Gérer la file',
  'orders.pending': 'En attente', 'orders.picking': 'Préparation', 'orders.awaitingPayment': 'Paiement attendu', 'orders.paid': 'Payées, non expédiées', 'orders.dispatched': 'Expédiées', 'orders.completed': 'Terminées', 'orders.cancelled': 'Annulées', 'orders.statusFilter': 'Statut de commande',
  'orders.searchLabel': 'Rechercher', 'orders.searchPlaceholder': 'Numéro de commande ou produit', 'orders.storeLabel': 'Boutique', 'orders.allStores': 'Toutes les boutiques connectées', 'orders.reset': 'Réinitialiser', 'orders.errorTitle': 'Impossible de charger les commandes', 'orders.errorFallback': 'Le service de commandes ne répond pas.', 'orders.emptyTitle': 'Aucune commande dans cette file', 'orders.emptyCopy': 'Synchronisez une boutique pour importer ses dernières commandes.', 'orders.emptyFilteredCopy': 'Aucune commande ne correspond aux filtres.', 'orders.clearFilters': 'Effacer les filtres',
  'orders.order': 'Commande', 'orders.items': 'Articles', 'orders.store': 'Boutique', 'orders.customer': 'Client', 'orders.cost': 'Coût', 'orders.shipping': 'Livraison', 'orders.created': 'Créée', 'orders.action': 'Action', 'orders.review': 'Vérifier', 'orders.itemCount': '{value} article(s)', 'orders.productCost': 'Coût produit', 'orders.shippingCost': 'Coût livraison', 'orders.unnamedItem': 'Produit boutique', 'orders.shopify': 'Shopify', 'orders.destination': 'Destination', 'orders.openFulfillment': 'Ouvrir le traitement', 'orders.resultCount': '{value} commandes', 'orders.previous': 'Page précédente', 'orders.next': 'Page suivante',
  'orders.sync': 'Synchroniser les commandes', 'orders.syncing': 'Synchronisation...', 'orders.syncLabel': 'Synchronisation boutique', 'orders.syncTitle': 'Importer les dernières commandes', 'orders.syncCopy': 'Choisissez une boutique autorisée. CoD demande les commandes sans les modifier dans Shopify.', 'orders.confirmSync': 'Synchroniser', 'orders.syncError': 'Impossible de synchroniser les commandes.',
}

const de = {
  'orders.kicker': 'Auftragssteuerung', 'orders.title': 'Shop-Bestellungen', 'orders.subtitle': 'Prüfe echte Bestellungen aus allen verbundenen Shops und übergib die richtige Arbeit an die Abwicklung.',
  'orders.summary': 'Bestellübersicht', 'orders.currentQueue': 'Bestellungen in dieser Warteschlange', 'orders.connectedStores': 'Verbundene Shops', 'orders.visibleOrders': 'Auf dieser Seite sichtbar', 'orders.pageOf': 'Seite {page} von {pages}', 'orders.nextAction': 'Nächste Aktion', 'orders.nextActionCopy': 'Aus der gewählten Warteschlange arbeiten', 'orders.reviewOrders': 'Bestellungen prüfen', 'orders.manageQueue': 'Warteschlange verwalten',
  'orders.pending': 'Ausstehend', 'orders.picking': 'Kommissionierung', 'orders.awaitingPayment': 'Warten auf Zahlung', 'orders.paid': 'Bezahlt, nicht versandt', 'orders.dispatched': 'Versandt', 'orders.completed': 'Abgeschlossen', 'orders.cancelled': 'Storniert', 'orders.statusFilter': 'Bestellstatus',
  'orders.searchLabel': 'Bestellungen suchen', 'orders.searchPlaceholder': 'Bestellnummer oder Produkttitel', 'orders.storeLabel': 'Shop', 'orders.allStores': 'Alle verbundenen Shops', 'orders.reset': 'Zurücksetzen', 'orders.errorTitle': 'Bestellungen konnten nicht geladen werden', 'orders.errorFallback': 'Der Bestelldienst hat nicht geantwortet.', 'orders.emptyTitle': 'Keine Bestellungen in dieser Warteschlange', 'orders.emptyCopy': 'Synchronisiere einen Shop, um neue Bestellungen zu importieren.', 'orders.emptyFilteredCopy': 'Keine Bestellung entspricht den Filtern.', 'orders.clearFilters': 'Filter löschen',
  'orders.order': 'Bestellung', 'orders.items': 'Artikel', 'orders.store': 'Shop', 'orders.customer': 'Kunde', 'orders.cost': 'Kosten', 'orders.shipping': 'Versand', 'orders.created': 'Erstellt', 'orders.action': 'Aktion', 'orders.review': 'Prüfen', 'orders.itemCount': '{value} Artikel', 'orders.productCost': 'Produktkosten', 'orders.shippingCost': 'Versandkosten', 'orders.unnamedItem': 'Shop-Produkt', 'orders.shopify': 'Shopify', 'orders.destination': 'Ziel', 'orders.openFulfillment': 'Abwicklung öffnen', 'orders.resultCount': '{value} Bestellungen', 'orders.previous': 'Vorherige Seite', 'orders.next': 'Nächste Seite',
  'orders.sync': 'Bestellungen synchronisieren', 'orders.syncing': 'Synchronisierung...', 'orders.syncLabel': 'Shop-Synchronisierung', 'orders.syncTitle': 'Neueste Bestellungen importieren', 'orders.syncCopy': 'Wähle einen autorisierten Shop. CoD liest Bestellungen, ohne sie in Shopify zu ändern.', 'orders.confirmSync': 'Synchronisieren', 'orders.syncError': 'Bestellungen konnten nicht synchronisiert werden.',
}

const pt = {
  'orders.kicker': 'Controle de pedidos', 'orders.title': 'Pedidos das lojas', 'orders.subtitle': 'Revise pedidos reais de todas as lojas conectadas e envie o trabalho certo para atendimento.',
  'orders.summary': 'Resumo dos pedidos', 'orders.currentQueue': 'Pedidos nesta fila', 'orders.connectedStores': 'Lojas conectadas', 'orders.visibleOrders': 'Visíveis nesta página', 'orders.pageOf': 'Página {page} de {pages}', 'orders.nextAction': 'Próxima ação', 'orders.nextActionCopy': 'Trabalhe pela fila selecionada', 'orders.reviewOrders': 'Revisar pedidos', 'orders.manageQueue': 'Gerenciar fila',
  'orders.pending': 'Pendentes', 'orders.picking': 'Separação', 'orders.awaitingPayment': 'Aguardando pagamento', 'orders.paid': 'Pagos, não enviados', 'orders.dispatched': 'Enviados', 'orders.completed': 'Concluídos', 'orders.cancelled': 'Cancelados', 'orders.statusFilter': 'Status do pedido',
  'orders.searchLabel': 'Buscar pedidos', 'orders.searchPlaceholder': 'Número do pedido ou produto', 'orders.storeLabel': 'Loja', 'orders.allStores': 'Todas as lojas conectadas', 'orders.reset': 'Redefinir', 'orders.errorTitle': 'Não foi possível carregar os pedidos', 'orders.errorFallback': 'O serviço de pedidos não respondeu.', 'orders.emptyTitle': 'Nenhum pedido nesta fila', 'orders.emptyCopy': 'Sincronize uma loja para importar os pedidos recentes.', 'orders.emptyFilteredCopy': 'Nenhum pedido corresponde aos filtros.', 'orders.clearFilters': 'Limpar filtros',
  'orders.order': 'Pedido', 'orders.items': 'Itens', 'orders.store': 'Loja', 'orders.customer': 'Cliente', 'orders.cost': 'Custo', 'orders.shipping': 'Envio', 'orders.created': 'Criado', 'orders.action': 'Ação', 'orders.review': 'Revisar', 'orders.itemCount': '{value} item(ns)', 'orders.productCost': 'Custo do produto', 'orders.shippingCost': 'Custo de envio', 'orders.unnamedItem': 'Produto da loja', 'orders.shopify': 'Shopify', 'orders.destination': 'Destino', 'orders.openFulfillment': 'Abrir atendimento', 'orders.resultCount': '{value} pedidos', 'orders.previous': 'Página anterior', 'orders.next': 'Próxima página',
  'orders.sync': 'Sincronizar pedidos', 'orders.syncing': 'Sincronizando...', 'orders.syncLabel': 'Sincronização da loja', 'orders.syncTitle': 'Importar pedidos recentes', 'orders.syncCopy': 'Escolha uma loja autorizada. A CoD solicita os pedidos sem alterá-los na Shopify.', 'orders.confirmSync': 'Sincronizar', 'orders.syncError': 'Não foi possível sincronizar os pedidos.',
}

const ar = {
  'orders.kicker': 'إدارة الطلبات', 'orders.title': 'طلبات المتاجر', 'orders.subtitle': 'راجع الطلبات الحقيقية من جميع المتاجر المتصلة وانقل العمل المناسب إلى التنفيذ.',
  'orders.summary': 'ملخص الطلبات', 'orders.currentQueue': 'الطلبات في هذه القائمة', 'orders.connectedStores': 'المتاجر المتصلة', 'orders.visibleOrders': 'الظاهرة في هذه الصفحة', 'orders.pageOf': 'الصفحة {page} من {pages}', 'orders.nextAction': 'الإجراء التالي', 'orders.nextActionCopy': 'العمل من القائمة المحددة', 'orders.reviewOrders': 'مراجعة الطلبات', 'orders.manageQueue': 'إدارة القائمة',
  'orders.pending': 'قيد الانتظار', 'orders.picking': 'تجهيز الطلب', 'orders.awaitingPayment': 'بانتظار الدفع', 'orders.paid': 'مدفوع ولم يشحن', 'orders.dispatched': 'تم الشحن', 'orders.completed': 'مكتمل', 'orders.cancelled': 'ملغي', 'orders.statusFilter': 'حالة الطلب',
  'orders.searchLabel': 'البحث في الطلبات', 'orders.searchPlaceholder': 'رقم الطلب أو اسم المنتج', 'orders.storeLabel': 'المتجر', 'orders.allStores': 'كل المتاجر المتصلة', 'orders.reset': 'إعادة ضبط', 'orders.errorTitle': 'تعذر تحميل الطلبات', 'orders.errorFallback': 'لم تستجب خدمة الطلبات.', 'orders.emptyTitle': 'لا توجد طلبات في هذه القائمة', 'orders.emptyCopy': 'زامن متجرا متصلا لاستيراد أحدث الطلبات.', 'orders.emptyFilteredCopy': 'لا توجد طلبات مطابقة للفلاتر.', 'orders.clearFilters': 'مسح الفلاتر',
  'orders.order': 'الطلب', 'orders.items': 'العناصر', 'orders.store': 'المتجر', 'orders.customer': 'العميل', 'orders.cost': 'التكلفة', 'orders.shipping': 'الشحن', 'orders.created': 'تاريخ الإنشاء', 'orders.action': 'الإجراء', 'orders.review': 'مراجعة', 'orders.itemCount': '{value} عنصر', 'orders.productCost': 'تكلفة المنتج', 'orders.shippingCost': 'تكلفة الشحن', 'orders.unnamedItem': 'منتج المتجر', 'orders.shopify': 'Shopify', 'orders.destination': 'الوجهة', 'orders.openFulfillment': 'فتح التنفيذ', 'orders.resultCount': '{value} طلب', 'orders.previous': 'الصفحة السابقة', 'orders.next': 'الصفحة التالية',
  'orders.sync': 'مزامنة الطلبات', 'orders.syncing': 'جارٍ المزامنة...', 'orders.syncLabel': 'مزامنة المتجر', 'orders.syncTitle': 'استيراد أحدث الطلبات', 'orders.syncCopy': 'اختر متجرا مصرحا. تقرأ CoD الطلبات من دون تعديلها في Shopify.', 'orders.confirmSync': 'مزامنة', 'orders.syncError': 'تعذرت مزامنة الطلبات.',
}

const ja = {
  'orders.kicker': '注文管理', 'orders.title': 'ストア注文', 'orders.subtitle': '接続済みストアの実注文を確認し、必要な作業をフルフィルメントへ進めます。',
  'orders.summary': '注文概要', 'orders.currentQueue': '現在の注文数', 'orders.connectedStores': '接続済みストア', 'orders.visibleOrders': 'このページの表示数', 'orders.pageOf': '{pages} ページ中 {page} ページ', 'orders.nextAction': '次の操作', 'orders.nextActionCopy': '選択中のキューから作業', 'orders.reviewOrders': '注文を確認', 'orders.manageQueue': 'キューを管理',
  'orders.pending': '保留中', 'orders.picking': 'ピッキング中', 'orders.awaitingPayment': '支払い待ち', 'orders.paid': '支払済み・未発送', 'orders.dispatched': '発送済み', 'orders.completed': '完了', 'orders.cancelled': 'キャンセル', 'orders.statusFilter': '注文ステータス',
  'orders.searchLabel': '注文を検索', 'orders.searchPlaceholder': '注文番号または商品名', 'orders.storeLabel': 'ストア', 'orders.allStores': 'すべての接続済みストア', 'orders.reset': 'リセット', 'orders.errorTitle': '注文を読み込めませんでした', 'orders.errorFallback': '注文サービスが応答しませんでした。', 'orders.emptyTitle': 'このキューに注文はありません', 'orders.emptyCopy': 'ストアを同期して最新注文を取り込みます。', 'orders.emptyFilteredCopy': '条件に一致する注文はありません。', 'orders.clearFilters': 'フィルターを解除',
  'orders.order': '注文', 'orders.items': '商品', 'orders.store': 'ストア', 'orders.customer': '顧客', 'orders.cost': 'コスト', 'orders.shipping': '配送', 'orders.created': '作成日', 'orders.action': '操作', 'orders.review': '確認', 'orders.itemCount': '{value} 点', 'orders.productCost': '商品コスト', 'orders.shippingCost': '配送コスト', 'orders.unnamedItem': 'ストア商品', 'orders.shopify': 'Shopify', 'orders.destination': '配送先', 'orders.openFulfillment': 'フルフィルメントを開く', 'orders.resultCount': '{value} 件', 'orders.previous': '前のページ', 'orders.next': '次のページ',
  'orders.sync': '注文を同期', 'orders.syncing': '同期中...', 'orders.syncLabel': 'ストア同期', 'orders.syncTitle': '最新注文を取り込む', 'orders.syncCopy': '認証済みストアを選択します。CoD は Shopify の注文を変更せずに取得します。', 'orders.confirmSync': '同期する', 'orders.syncError': '注文を同期できませんでした。',
}

const ko = {
  'orders.kicker': '주문 관리', 'orders.title': '스토어 주문', 'orders.subtitle': '연결된 모든 스토어의 실제 주문을 검토하고 필요한 작업을 풀필먼트로 보냅니다.',
  'orders.summary': '주문 요약', 'orders.currentQueue': '현재 대기열 주문', 'orders.connectedStores': '연결된 스토어', 'orders.visibleOrders': '현재 페이지 표시', 'orders.pageOf': '{pages}페이지 중 {page}페이지', 'orders.nextAction': '다음 작업', 'orders.nextActionCopy': '선택한 대기열에서 처리', 'orders.reviewOrders': '주문 검토', 'orders.manageQueue': '대기열 관리',
  'orders.pending': '대기 중', 'orders.picking': '피킹 중', 'orders.awaitingPayment': '결제 대기', 'orders.paid': '결제 완료・미배송', 'orders.dispatched': '배송됨', 'orders.completed': '완료', 'orders.cancelled': '취소됨', 'orders.statusFilter': '주문 상태',
  'orders.searchLabel': '주문 검색', 'orders.searchPlaceholder': '주문 번호 또는 상품명', 'orders.storeLabel': '스토어', 'orders.allStores': '모든 연결 스토어', 'orders.reset': '초기화', 'orders.errorTitle': '주문을 불러오지 못했습니다', 'orders.errorFallback': '주문 서비스가 응답하지 않았습니다.', 'orders.emptyTitle': '이 대기열에 주문이 없습니다', 'orders.emptyCopy': '스토어를 동기화하여 최신 주문을 가져오세요.', 'orders.emptyFilteredCopy': '필터와 일치하는 주문이 없습니다.', 'orders.clearFilters': '필터 지우기',
  'orders.order': '주문', 'orders.items': '상품', 'orders.store': '스토어', 'orders.customer': '고객', 'orders.cost': '비용', 'orders.shipping': '배송', 'orders.created': '생성일', 'orders.action': '작업', 'orders.review': '검토', 'orders.itemCount': '{value}개', 'orders.productCost': '상품 비용', 'orders.shippingCost': '배송 비용', 'orders.unnamedItem': '스토어 상품', 'orders.shopify': 'Shopify', 'orders.destination': '배송지', 'orders.openFulfillment': '풀필먼트 열기', 'orders.resultCount': '{value}개 주문', 'orders.previous': '이전 페이지', 'orders.next': '다음 페이지',
  'orders.sync': '주문 동기화', 'orders.syncing': '동기화 중...', 'orders.syncLabel': '스토어 동기화', 'orders.syncTitle': '최신 주문 가져오기', 'orders.syncCopy': '승인된 스토어를 선택하세요. CoD는 Shopify 주문을 변경하지 않고 가져옵니다.', 'orders.confirmSync': '동기화', 'orders.syncError': '주문을 동기화하지 못했습니다.',
}

const ru = {
  'orders.kicker': 'Управление заказами', 'orders.title': 'Заказы магазинов', 'orders.subtitle': 'Проверяйте реальные заказы подключенных магазинов и передавайте нужную работу в выполнение.',
  'orders.summary': 'Сводка заказов', 'orders.currentQueue': 'Заказы в этой очереди', 'orders.connectedStores': 'Подключенные магазины', 'orders.visibleOrders': 'На этой странице', 'orders.pageOf': 'Страница {page} из {pages}', 'orders.nextAction': 'Следующее действие', 'orders.nextActionCopy': 'Работа с выбранной очередью', 'orders.reviewOrders': 'Проверить заказы', 'orders.manageQueue': 'Управлять очередью',
  'orders.pending': 'Ожидают', 'orders.picking': 'Комплектуются', 'orders.awaitingPayment': 'Ожидают оплаты', 'orders.paid': 'Оплачены, не отправлены', 'orders.dispatched': 'Отправлены', 'orders.completed': 'Завершены', 'orders.cancelled': 'Отменены', 'orders.statusFilter': 'Статус заказа',
  'orders.searchLabel': 'Поиск заказов', 'orders.searchPlaceholder': 'Номер заказа или товар', 'orders.storeLabel': 'Магазин', 'orders.allStores': 'Все подключенные магазины', 'orders.reset': 'Сбросить', 'orders.errorTitle': 'Не удалось загрузить заказы', 'orders.errorFallback': 'Сервис заказов не ответил.', 'orders.emptyTitle': 'В этой очереди нет заказов', 'orders.emptyCopy': 'Синхронизируйте магазин, чтобы импортировать новые заказы.', 'orders.emptyFilteredCopy': 'Нет заказов, соответствующих фильтрам.', 'orders.clearFilters': 'Очистить фильтры',
  'orders.order': 'Заказ', 'orders.items': 'Товары', 'orders.store': 'Магазин', 'orders.customer': 'Клиент', 'orders.cost': 'Стоимость', 'orders.shipping': 'Доставка', 'orders.created': 'Создан', 'orders.action': 'Действие', 'orders.review': 'Проверить', 'orders.itemCount': '{value} шт.', 'orders.productCost': 'Стоимость товара', 'orders.shippingCost': 'Стоимость доставки', 'orders.unnamedItem': 'Товар магазина', 'orders.shopify': 'Shopify', 'orders.destination': 'Назначение', 'orders.openFulfillment': 'Открыть выполнение', 'orders.resultCount': '{value} заказов', 'orders.previous': 'Предыдущая страница', 'orders.next': 'Следующая страница',
  'orders.sync': 'Синхронизировать заказы', 'orders.syncing': 'Синхронизация...', 'orders.syncLabel': 'Синхронизация магазина', 'orders.syncTitle': 'Импортировать новые заказы', 'orders.syncCopy': 'Выберите авторизованный магазин. CoD получает заказы, не изменяя их в Shopify.', 'orders.confirmSync': 'Синхронизировать', 'orders.syncError': 'Не удалось синхронизировать заказы.',
}

const actionEn = {'orders.customerAndDelivery':'Customer and delivery','orders.firstName':'First name','orders.lastName':'Last name','orders.addressLine':'Address','orders.city':'City','orders.province':'State / province','orders.postcode':'Postal code','orders.country':'Country','orders.phone':'Phone','orders.saveAddress':'Save address','orders.orderNote':'Internal order note','orders.orderNotePlaceholder':'Add instructions for this order','orders.saveNote':'Save note','orders.loadShipping':'Load available methods','orders.saveShipping':'Save shipping method','orders.working':'Working...','orders.startFulfillment':'Approve and start fulfillment','orders.actionFailed':'The order update failed.','orders.addressSaved':'Delivery address saved.','orders.noteSaved':'Order note saved.','orders.shippingSaved':'Shipping method saved.','orders.fulfillmentConfirm':'Approve this order and send it to fulfillment?','orders.fulfillmentStarted':'Order moved to fulfillment.'}
const actionZh = {'orders.customerAndDelivery':'客户与配送信息','orders.firstName':'名字','orders.lastName':'姓氏','orders.addressLine':'详细地址','orders.city':'城市','orders.province':'省/州','orders.postcode':'邮编','orders.country':'国家','orders.phone':'电话','orders.saveAddress':'保存地址','orders.orderNote':'内部订单备注','orders.orderNotePlaceholder':'添加此订单的处理说明','orders.saveNote':'保存备注','orders.loadShipping':'获取可用物流','orders.saveShipping':'保存物流方式','orders.working':'正在处理...','orders.startFulfillment':'确认并开始履约','orders.actionFailed':'订单更新失败。','orders.addressSaved':'配送地址已保存。','orders.noteSaved':'订单备注已保存。','orders.shippingSaved':'物流方式已保存。','orders.fulfillmentConfirm':'确认该订单并发送到履约队列？','orders.fulfillmentStarted':'订单已进入履约队列。'}
export const ordersMessages = {
  'en-US': {...en,...actionEn}, 'zh-CN': {...zh,...actionZh}, 'es-ES': {...es,...actionEn}, 'fr-FR': {...fr,...actionEn}, 'de-DE': {...de,...actionEn},
  'pt-BR': {...pt,...actionEn}, 'ar-SA': {...ar,...actionEn}, 'ja-JP': {...ja,...actionEn}, 'ko-KR': {...ko,...actionEn}, 'ru-RU': {...ru,...actionEn},
}
